"""test migration

Revision ID: fc0e46a609f5
Revises: 
Create Date: 2025-12-09 11:17:10.727163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0e46a609f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_generation_sessions_session_id'), table_name='generation_sessions')
    op.drop_table('generation_sessions')
    op.drop_index(op.f('ix_generation_attempts_id'), table_name='generation_attempts')
    op.drop_table('generation_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_attempts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.Column('prompt', sa.TEXT(), nullable=True),
    sa.Column('reference_image', sa.TEXT(), nullable=True),
    sa.Column('reference_images', sa.TEXT(), nullable=True),
    sa.Column('output_path', sa.TEXT(), nullable=True),
    sa.Column('attempt_number', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['generation_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_attempts_id'), 'generation_attempts', ['id'], unique=False)
    op.create_table('generation_sessions',
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('reference_image', sa.VARCHAR(), nullable=True),
    sa.Column('reference_images', sa.TEXT(), nullable=True),
    sa.Column('input_prompt', sa.TEXT(), nullable=False),
    sa.Column('output_path', sa.VARCHAR(), nullable=True),
    sa.Column('approved', sa.BOOLEAN(), nullable=True),
    sa.Column('attempts', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_generation_sessions_session_id'), 'generation_sessions', ['session_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(), nullable=False),
    sa.Column('lastname', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('user_type', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###
